### ISSUE TITLE
Exception with openjdk

### ISSUE THREAD

**Issue by devnewton** [joular/joularjx#78]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/management/OperatingSystemMXBean
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.base/java.lang.Class.getDeclaredMethod(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
```

**Comment by devnewton** [comment]
I use a Docker image with openjdk and maven ( maven:3.9.9-eclipse-temurin-17 https://github.com/carlossg/docker-maven/blob/8cfe24baffa5b250f7bb2d31ce233fc28f3c4f20/eclipse-temurin-17/Dockerfile ) on Ubuntu.

The full java distribution information : OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (17.0.13+11, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64).

**Comment by adelnoureddine** [comment]
Hi, it may be possible that OperatingSystemMXBean class isn't available in your Java distribution in Docker.

**Comment by theobisproject** [comment]
I failed to reproduce your issue with the JDK base image used in the Dockerfile you linked.

Running the JDK on a bare metal Ubuntu 24.04 worked as expected
```
$ sudo /opt/jdk-17.0.13+11/bin/java -javaagent:target/joularjx-3.0.0.jar -version
17/11/2024 09:18:51.546 - [INFO] - +---------------------------------+
17/11/2024 09:18:51.546 - [INFO] - | JoularJX Agent Version 3.0.0    |
17/11/2024 09:18:51.546 - [INFO] - +---------------------------------+
17/11/2024 09:18:51.560 - [INFO] - Results will be stored in joularjx-result/56857-1731831531558/
17/11/2024 09:18:51.567 - [INFO] - Initializing for platform: 'linux' running on architecture: 'amd64'
17/11/2024 09:18:51.574 - [INFO] - Please wait while initializing JoularJX...
17/11/2024 09:18:52.581 - [INFO] - Initialization finished
17/11/2024 09:18:52.581 - [INFO] - Started monitoring application with ID 56857
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode, sharing)
17/11/2024 09:18:53.632 - [INFO] - JoularJX finished monitoring application with ID 56857
17/11/2024 09:18:53.632 - [INFO] - Program consumed 5.54 joules
17/11/2024 09:18:53.635 - [INFO] - Energy consumption of methods and filtered methods written to files
```
This means the JDK should not throw the `NoClassDefFoundError`.

Running in a Docker container exits early for me since the RAPL interface is not available in the container
```
17/11/2024 08:30:37.340 - [INFO] - Could not locate config.properties, will use default values
17/11/2024 08:30:37.341 - [INFO] - +---------------------------------+
17/11/2024 08:30:37.341 - [INFO] - | JoularJX Agent Version 3.0.0    |
17/11/2024 08:30:37.341 - [INFO] - +---------------------------------+
17/11/2024 08:30:37.353 - [INFO] - Results will be stored in joularjx-result/1-1731832237351/
17/11/2024 08:30:37.361 - [INFO] - Initializing for platform: 'linux' running on architecture: 'amd64'
17/11/2024 08:30:37.361 - [SEVERE] - Platform not supported. Exiting...
```

The Dockerfile I used
```Dockerfile
FROM eclipse-temurin:17-jdk

RUN apt-get update \
  && apt-get install -y ca-certificates curl git openssh-client --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

COPY target/joularjx-3.0.0.jar /root/

CMD ["java", "-javaagent:/root/joularjx-3.0.0.jar", "-version"]
```

Have you done any specific mounts for your Docker container to be able to use the RAPL interface? Anything changed in the properties file to get the agent to try and initialize the `OperatingSystemMXBean`?
